Prisma chan password
SamanthaLHC/ft_transcendence pull request #36
Opened 2023-10-23 16:34 UTC by basile41

Add:
-Password for the Channel table in DB
-modification of the create and join requests to manage passwords for protected channels
-Password are hashed before being stored in DB

To test:
-create a channel with a password
-join a protected channel with this request:
POST  /chat/channel/join/[ID of the channel] 
body:
```json
{
    "password": "password_of_the_channel"
}
```

2023-10-24 14:21 UTC, WickiRiama requested changes
The creation of a protected channel works, the password is correctly hashed in the database and joining a password protected channel works.

You should add a DTO to protect the password given in the POST request.

2023-10-24 15:09 UTC, SamanthaLHC requested changes
- [  ] pop up when create protected channel without a compliet password (uppercase, digit etc)
- [  ] join providing the correct password
- [  ] warning when attempting to join a chan with a bad password
- [  ] cannot create a channel with the same name as another one
- [ ] join a public channel 


Joining a public chann without password is impossible.

2023-10-25 16:09 UTC, SamanthaLHC commented
join will be corrected in another branch

2023-10-25 16:10 UTC, SamanthaLHC approved these changes

2023-10-25 16:12 UTC, merged