Game with friend
SamanthaLHC/ft_transcendence pull request #50
Opened 2023-11-03 14:53 UTC by geekprod27

Add game invitation

TO test

- [ ] aller sur la page profile dun autres user et clicker sur invite game (cela devrai ouvrir les mp avec un message "Tu veux jouer ?" le sender ne dois pas voir les bouton accepter ni refuser,
- [ ] si le sender ce deconecte du chat la demande est editer 
- [ ] si le receveur clique sur refuser le message est editer fesant disparaitre les bouton
- [ ] si le receveur accepter cela redirige les 2 user vers la page "/gamefriend?id-[USERID]" ou [USERID] est id de lautre user puis le jeu ce lance

2023-11-03 15:31 UTC, SamanthaLHC requested changes
important: verifyAsync peut envoyer des exceptions si le token est invalide ou expiré il faut donc mettre cet appel dans un try/catch -> c'est ce qui permet de fixer les problemes avec les cors et les crash

2023-11-03 15:31 UTC, SamanthaLHC commented on backend/src/chat/chat.gateway.ts
> +		const payload = await this.jwtService.verifyAsync(
- Pourquoi as tu besoin d' utiliser jwtService plutot que AuthGuard ?

- important: verifyAsync peut envoyer des exceptions si le token est invalide ou expiré il faut donc mettre cet appel dans un try/catch -> c'est ce qui permet de fixxer les problemes avec les cors et les crash

2023-11-03 16:52 UTC, basile41 approved these changes
fixed : there were potential uncaught exceptions getting jwt data

The PR seems ok

2023-11-04 14:42 UTC, SamanthaLHC approved these changes

2023-11-06 14:10 UTC, SamanthaLHC requested changes
``` PrismaClientValidationError: 
backend        | Invalid `this.prisma.messages.updateMany()` invocation in
backend        | /back/src/chat/chat.gateway.ts:56:30
backend        | 
backend        |   53 async handleDisconnect(@ConnectedSocket() client: Socket) {
backend        |   54 	let findSocket = this.sockets.find(sockets => sockets.socket === client)
backend        |   55 	let userId = findSocket.user
backend        | → 56 	await this.prisma.messages.updateMany({
backend        |        where: {
backend        |          type: "GAME",
backend        |      +   senderId: {
backend        |      +     equals: Int | IntFieldRefInput,
backend        |      +     in: Int[] | ListIntFieldRefInput,
backend        |      +     notIn: Int[] | ListIntFieldRefInput,
backend        |      +     lt: Int | IntFieldRefInput,
backend        |      +     lte: Int | IntFieldRefInput,
backend        |      +     gt: Int | IntFieldRefInput,
backend        |      +     gte: Int | IntFieldRefInput,
backend        |      +     not: Int | NestedIntFilter
backend        |      +   }
backend        |        },
backend        |        data: {
backend        |          type: "MESSAGE",
backend        |          content: "[INVITATION JEU] - La personne a quite le chat"
backend        |        }
backend        |      })
backend        | 
backend        | Argument `senderId` is missing.
backend        |     at xn (/back/node_modules/@prisma/client/runtime/library.js:116:5852)
backend        |     at vn.handleRequestError (/back/node_modules/@prisma/client/runtime/library.js:123:6429)
backend        |     at vn.handleAndLogRequestError (/back/node_modules/@prisma/client/runtime/library.js:123:6119)
backend        |     at vn.request (/back/node_modules/@prisma/client/runtime/library.js:123:5839)
backend        |     at l (/back/node_modules/@prisma/client/runtime/library.js:128:9763)
backend        |     at ChatGateway.handleDisconnect (/back/src/chat/chat.gateway.ts:56:3)
backend        | ```

2023-11-08 14:33 UTC, SamanthaLHC approved these changes
Le crash lors du refresh ne semble plus être présent, le comportement est en accord avec les attendus!

2023-11-08 14:33 UTC, merged